<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>chronos_capture</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>73449b19-1840-467f-9fa8-79628a4a958f</testSuiteGuid>
   <testCaseLink>
      <guid>42cfbf79-67a0-400a-b228-631b02b79737</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/47news/visitSite</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3499687e-65ea-4c3b-bde7-1dc745b7d0fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6ea7cf4-2f32-4a4c-a181-35bad53b84e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>915943ec-566f-4810-b580-c9547228f531</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/VT/backupCurrentTSuiteResult</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fbe33037-8fca-486f-ba14-161f49946a80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/VT/restorePreviousTSuiteResult</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>737523c0-e55e-4415-a49c-9d1015dee824</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
