import com.kazurayam.visualtesting.GlobalVariableHelpersTest
import com.kazurayam.visualtesting.ImageCollectionDifferDriverTest
import com.kazurayam.visualtesting.ManagedGlobalVariableTest
import com.kazurayam.visualtesting.VisualTestingListenerImplTest

CustomKeywords.'com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner'(GlobalVariableHelpersTest.class)
CustomKeywords.'com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner'(ImageCollectionDifferDriverTest.class)
CustomKeywords.'com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner'(ManagedGlobalVariableTest.class)
CustomKeywords.'com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner'(VisualTestingListenerImplTest.class)

1